dist: xenial
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4
    - php: 7.4
      env: SETUP=lowest
    - php: 8.0
    - php: 8.0
      env: SETUP=lowest

cache:
  directories:
  - $HOME/.composer/cache

install:
- if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
- if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit --verbose
